version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    volumes:
      - /media/NewHDD/calendar/.docker/rabbitmq/etc/:/var/run/rabbitmq/
      - /media/NewHDD/calendar/.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - /media/NewHDD/calendar/.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 15666:15672
      - 15667:5672
    environment:
      # provide your credentials here
      - RABBITMQ_DEFAULT_PASS=hagiang123
      - RABBITMQ_DEFAULT_USER=binhhg
    networks:
      - calendar
    restart: always
  mongodb:
    image: mongo:latest
    ports:
      - '8016:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=binhhg
      - MONGO_INITDB_ROOT_PASSWORD=hagiang123
    command: mongod
    volumes:
      - /media/NewHDD/calendar/mongo-data:/data/db
    networks:
      - calendar
    restart: always
  calendar:
    image: "calendar:latest"
    ports:
      - '8502:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB_SERVERS: 'mongodb:27017'
      DB_PORT: "3306"
      DB_USER: 'binhhg'
      DB_PASS: 'hagiang123'
      USER_URL: 'http://user:3000'
    networks:
      - calendar
    restart: always
  user:
    image: "user:latest"
    ports:
      - '8501:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB_SERVERS: 'mongodb:27017'
      DB_PORT: "3306"
      DB_USER: 'binhhg'
      DB_PASS: 'hagiang123'
    networks:
      - calendar
    restart: always
  calendar-web:
    image: "calendar-web:latest"
    ports:
      - '8500:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
    networks:
      - calendar
    restart: always
networks:
  calendar:
    driver: bridge
